# Generated by Django 3.2.5 on 2021-09-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=128)),
                ('match_stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_fielder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='cricket.player')),
                ('bowler_of_the_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='cricket.player')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss', to='cricket.team')),
                ('man_of_the_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man', to='cricket.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cricket.match')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win', to='cricket.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cricket.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_1', to='cricket.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_2', to='cricket.team'),
        ),
    ]
